platform :ios, '18.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  # Weakly link Translation.framework so the app doesn't crash on iOS < 17.4
  runner_project = installer.aggregate_targets.first&.user_project
  if runner_project
    runner_project.native_targets.select { |t| t.name == 'Runner' }.each do |target|
      target.build_configurations.each do |config|
        flags = Array(config.build_settings['OTHER_LDFLAGS'] || ['$(inherited)'])
        unless flags.include?('-weak_framework')
          config.build_settings['OTHER_LDFLAGS'] = flags + ['-weak_framework', 'Translation']
        end
      end
    end
    runner_project.save
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      if target.name == 'flutter_background_service_ios'
        config.build_settings['CLANG_ENABLE_MODULE_VERIFIER'] = 'NO'
        config.build_settings['ENABLE_MODULE_VERIFIER'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = '$(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/Flutter"'
      end
      if target.name == 'permission_handler_apple'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'COCOAPODS=1']
        definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        definitions = [definitions] unless definitions.is_a?(Array)
        definitions << 'PERMISSION_BLUETOOTH=1' unless definitions.include?('PERMISSION_BLUETOOTH=1')
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
      end
    end
  end

  # flutter_background_service_ios 5.0.3 compatibility fixes for use_frameworks! +
  # modular headers.
  header = File.expand_path(
    '../.symlinks/plugins/flutter_background_service_ios/ios/Classes/FlutterBackgroundServicePlugin.h',
    __FILE__
  )
  if File.exist?(header)
    content = File.read(header)
    content.sub!(
      '#import <Flutter/Flutter.h>',
      "#if __has_include(<Flutter/Flutter.h>)\n#import <Flutter/Flutter.h>\n#else\n@protocol FlutterPlugin;\n@protocol FlutterPluginRegistrar;\n@class FlutterEngine;\n#endif"
    ) unless content.include?('__has_include(<Flutter/Flutter.h>)')

    unless content.include?('registerWithRegistrar:')
      content.sub!(
        /(\+ \(void\)registerEngine:.*?;)/,
        "+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar;\n\\1"
      )
    end
    File.write(header, content)
  end

  impl = File.expand_path(
    '../.symlinks/plugins/flutter_background_service_ios/ios/Classes/FlutterBackgroundServicePlugin.m',
    __FILE__
  )
  if File.exist?(impl)
    content = File.read(impl)
    unless content.include?('__has_include(<Flutter/Flutter.h>)')
      content.sub!(
        '#import "FlutterBackgroundServicePlugin.h"',
        "#import \"FlutterBackgroundServicePlugin.h\"\n#if __has_include(<Flutter/Flutter.h>)\n#import <Flutter/Flutter.h>\n#endif"
      )
      File.write(impl, content)
    end
  end

  umbrella = File.expand_path(
    'Pods/Target Support Files/flutter_background_service_ios/flutter_background_service_ios-umbrella.h',
    __dir__
  )
  if File.exist?(umbrella)
    content = File.read(umbrella)
    content.gsub!(
      '#import "FlutterBackgroundServicePlugin.h"',
      '#import <flutter_background_service_ios/FlutterBackgroundServicePlugin.h>'
    )
    File.write(umbrella, content)
  end
end
